Update Zoom module to v1
friggframework/api-module-library pull request #8
Opened 2024-05-27 19:40 UTC by igorschechtel

Removed:
- `manager.js` and `manager.test.js` files
- Models folder

Added:
- `package.json` file
- `definition.js` file
- Tests (`api.test.js` and `auther.test.js`)

2024-05-29 23:08 UTC, leofmds requested changes
Looks good, just a minor change

2024-05-29 23:08 UTC, leofmds commented on packages/zoom/api.js
> +        this.redirect_uri = process.env.REDIRECT_URI;
You can remove this line. The parent class will handle the `redirect_uri` attribution. The user needs to pass the variable to work properly, but it is best than assigning the env to the redirect every time

2024-05-30 23:15 UTC, leofmds approved these changes
All good 👍🏻

2024-07-16 14:47 UTC, MichaelRyanWebber commented
This has been merged as part of https://github.com/friggframework/api-module-library/pull/10

2024-07-16 14:47 UTC, closed without merging